### ISSUE TITLE
Use of the library

### ISSUE THREAD

**Issue by ngophuc** [brandon-kohn/clipper-lib#2]
Hello,

I am interested in your code of polygon clipping. I downloaded and compiled your code on git but I don't know how to use it. Could you please explain how to include the complied library into a code ? if you have a simple example of a C/C++ projet with clipper-lib, I would be very happy to have it.

Many thanks,
P.

**Comment by merwaaan** [comment]
This repository is a fork of ClipperLib. You can access the original documentation [here](http://www.angusj.com/delphi/clipper.php)

**Comment by ngophuc** [comment]
Thank you !
